services:
  web:
    container_name: webapp
    build:
      context: .  # Use the current directory
      dockerfile: Dockerfile 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "${WEB_APP_HTTP_PORT}:8080"

  database:
    image: postgres
    container_name: database
    environment: 
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - C:/Users/Murav/Documents/Docker-server-Postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment: 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - database